spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/monolith_authdb   # ðŸ‘ˆ host Ã© "postgres", NÃƒO "localhost"
        username: auth
        password: authpwd
    jpa:
        hibernate:
            ddl-auto: validate
    flyway:
        enabled: true
security:
    access-jwt:
        secret: "chaveParaPropositoDeTestesApenasNaoUsarEmProducao" # Trocar na produÃ§Ã£o
        expiration: 900000  # 15 minutos em milissegundos

    refresh-token:
        expiration: 2592000000 # 30 dias em milissegundos

